# frozen_string_literal: true

source 'https://rubygems.org'

ruby '3.3.10'

gem 'automation_helpers', '~> 6.0'
gem 'rubocop', '~> 1.78.0'
gem 'rubocop-performance', '~> 1.23.0'
gem 'selenium-webdriver', '4.31.0'
gem 'site_prism', '~> 5.0'
