# frozen_string_literal: true

source 'https://rubygems.org'

gem 'automation_helpers', '~> 4.0'
gem 'rspec', '~> 3.10'
gem 'rubocop', '~> 1.19.0'
gem 'rubocop-performance', '~> 1.11.0'
gem 'selenium-webdriver', '~> 4.0.0'
gem 'site_prism', '~> 3.7'
gem 'webdrivers', '~> 4.5'
