require:
- rubocop-performance
- rubocop-rspec

AllCops:
  Exclude:
    - 'sample_answers/*.rb'

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Layout/LineLength:
  Max: 140

Lint/StructNewOverride:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Metrics/BlockLength:
  Max: 75

Style/ExponentialNotation:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
