require:
- rubocop-performance
- rubocop-rspec

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Metrics/BlockLength:
  Max: 75

RSpec/DescribedClass:
  Enabled: false

RSpec/PredicateMatcher:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
