plugins:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable

Naming/MethodParameterName:
  AllowedNames:
    - a
    - b
    - c
    - d

RSpec/DescribeClass:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false
