require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  NewCops: enable

Metrics/BlockLength:
  Enabled: false

Naming/MethodParameterName:
  AllowedNames:
    - a
    - b
    - c
    - d

RSpec/DescribeClass:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Style/SymbolArray:
  Enabled: false
