require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  NewCops: enable

Lint/EmptyClass:
  Enabled: false

Layout/TrailingWhitespace:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false
