require:
  - rubocop-performance
  - rubocop-rspec

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Metrics/BlockLength:
  Max: 100

Style/HashEachMethods:
  Enabled: true
  Exclude:
    - 'spec/rolling_spec.rb'

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
