AllCops:
  NewCops: disable

Lint/InterpolationCheck:
  Exclude:
    - 'spec/1-easy/strings_spec.rb'

Lint/LiteralAsCondition:
  Exclude:
    - 'spec/2-medium/control_statements_spec.rb'

Lint/MissingSuper:
  Exclude:
    - 'spec/3-hard/message_passing_spec.rb'

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Lint/UnreachableCode:
  Exclude:
  - 'spec/2-medium/methods_spec.rb'
  - 'spec/2-medium/modules_spec.rb'

Lint/UnusedMethodArgument:
  Exclude:
  - 'spec/3-hard/message_passing_spec.rb'

Lint/UselessAssignment:
  Exclude:
    - 'spec/1-easy/strings_spec.rb'
    - 'spec/2-medium/exceptions_spec.rb'
    - 'spec/3-hard/pass_by_original_reference_spec.rb'

Lint/Void:
  Exclude:
  - 'spec/2-medium/methods_spec.rb'

Metrics/BlockLength:
  Max: 150

Naming/AccessorMethodName:
  Exclude:
  - 'spec/2-medium/classes_spec.rb'
  - 'spec/2-medium/modules_spec.rb'

Naming/MethodParameterName:
  Exclude:
  - 'spec/2-medium/methods_spec.rb'

Security/Eval:
  Exclude:
  - 'spec/2-medium/methods_spec.rb'

Security/Open:
  Enabled: false

Style/CharacterLiteral:
  Exclude:
    - 'spec/1-easy/strings_spec.rb'

Style/ConditionalAssignment:
  Exclude:
  - 'spec/2-medium/control_statements_spec.rb'

Style/Documentation:
  Enabled: false

Style/EvalWithLocation:
  Exclude:
  - 'spec/2-medium/classes_spec.rb'

Style/EvenOdd:
  Exclude:
  - 'spec/2-medium/control_statements_spec.rb'
  - 'spec/2-medium/iteration_spec.rb'
  - 'spec/2-medium/open_classes_spec.rb'

Style/For:
  Exclude:
  - 'spec/2-medium/control_statements_spec.rb'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/IfUnlessModifier:
  Exclude:
  - 'spec/2-medium/control_statements_spec.rb'

Style/InfiniteLoop:
  Exclude:
  - 'spec/2-medium/control_statements_spec.rb'

Style/MutableConstant:
  Enabled: false

Style/MissingRespondToMissing:
  Exclude:
  - 'spec/3-hard/message_passing_spec.rb'

Style/PercentLiteralDelimiters:
  Exclude:
  - 'spec/1-easy/strings_spec.rb'

Style/PerlBackrefs:
  Exclude:
  - 'spec/2-medium/regular_expressions_spec.rb'

Style/RaiseArgs:
  Exclude:
  - 'spec/2-medium/exceptions_spec.rb'

Style/RedundantBegin:
  Exclude:
  - 'spec/1-easy/nil_spec.rb'

Style/RedundantSelf:
  Exclude:
  - 'spec/2-medium/methods_spec.rb'

Style/SafeNavigation:
  Exclude:
  - 'spec/3-hard/sandwich_code_spec.rb'

Style/SelfAssignment:
  Exclude:
  - 'spec/2-medium/control_statements_spec.rb'

Style/SignalException:
  Exclude:
  - 'spec/2-medium/exceptions_spec.rb'

Style/StringLiterals:
  Exclude:
  - 'spec/1-easy/strings_spec.rb'

Style/SymbolArray:
  Enabled: false

Style/SymbolProc:
  Exclude:
  - 'spec/1-easy/symbols_spec.rb'

Style/TrivialAccessors:
  Exclude:
  - 'spec/2-medium/classes_spec.rb'
  - 'spec/2-medium/class_methods_spec.rb'

Style/WhileUntilModifier:
  Exclude:
  - 'spec/3-hard/sandwich_code_spec.rb'

Style/WordArray:
  Enabled: false
