inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable

# These offenses are the initial introduction to the format
RSpec/RepeatedExample:
  Exclude:
    - spec/2-medium/control_statements_spec.rb
    - spec/2-medium/iteration_spec.rb
    - spec/3-hard/block_spec.rb

# These offenses are the initial introduction to the format
Style/EmptyLiteral:
  Exclude:
    - spec/2-medium/arrays_spec.rb
    - spec/2-medium/hashes_spec.rb

# This offense is the initial introduction to the format
Style/RedundantFetchBlock:
  Exclude:
    - spec/2-medium/hashes_spec.rb

# This offense is the initial introduction to the format
Style/StringLiterals:
  Exclude:
    - spec/1-easy/strings_spec.rb

# This offense is the initial introduction to the format
Style/WordArray:
  Exclude:
    - spec/2-medium/arrays_spec.rb
